### ISSUE TITLE
Make module translatable

### ISSUE THREAD

**Issue by paviro** [RedNax67/MMM-WunderGround#1]
It would be awesome if you'd make the module [translatable](https://github.com/MichMich/MagicMirror/tree/master/modules#gettranslations)!

**Comment by RedNax67** [comment]
UPDATE: Translation supported.... but like the original weatherforecast module, it only translates LOADING :)

Well, there isn't really any text in the module itself anymore. Anything readable comes from weather underground which will provide it in the language specified...

**Comment by paviro** [comment]
Here is another one else ;)
`Please set the correct winderground <i>apikey</i> in the config for module: " + this.name + "."`

**Comment by RedNax67** [comment]
Okok, added proper translation implementation. :D Feel free to send pull requests with more languages... Although i feel this particular translation should be in the core files.

**Comment by paviro** [comment]
Why don't you add it without the mention of winderground but just generic api key?

**Comment by RedNax67** [comment]
The translation is already generic, the modulename gets added in the module itself..

```
wrapper.innerHTML = this.translate('APIKEY') + this.name + ".";
```

**Comment by paviro** [comment]
Ah haven't checked the new translation, we'll send a pull request to Michael I am sure he'll add it :)
