### ISSUE TITLE
it stops updating

### ISSUE THREAD

**Issue by dinkybluebug** [RedNax67/MMM-WunderGround#13]
Hi - my mmm-Wunderground module keeps freezing and doesnt update.  it works fine for a few hours, and then stops....and then doesn't update ever after this - with other modules working fine - including the clock.  I can get it working if I restart the mirror

Any ideas whats going on?

could it be because node got an update?

**Comment by ostfilinchen** [comment]
@dinkybluebug: i also have the same error. i thought, the Software Needs an update. So i updated with sudo apt-get update && sudo apt-get dist-upgrade.

The error remains.... i think the updatefunction in the module has an Problem... :-/

**Comment by lsumner4** [comment]
I have the same issue. I've looked around and seen that it is somewhat common but nobody has posted a solution.

**Comment by ostfilinchen** [comment]
I work on a solution. I think it's a not implmented errorhandling with the sunrise/sunset times. In some cases the Module gets a wrong json File back. That seems produce  the error.

**Comment by RedNax67** [comment]
Added a commit just now which should resolve the issue.. Please test!

**Comment by ostfilinchen** [comment]
i updated this module and test this. Tomorrow i give u a Feedback.

**Comment by dinkybluebug** [comment]
Can't test this until Friday, but thanks for the update.

**Comment by ostfilinchen** [comment]
It works for 6 times and then i get the error, that this key does not exist.

**Comment by RedNax67** [comment]
How fast are you updating? ie what is your updateinterval?

**Comment by ostfilinchen** [comment]
my initialLoadDelay is 1000

my updateIntervall is still Default (10 Minutes)

**Comment by lsumner4** [comment]
@RedNax67 It appears to be working for me now, thanks!

**Comment by dinkybluebug** [comment]
Works for me.... thanks!
