### ISSUE TITLE
Blank mirror

### ISSUE THREAD

**Issue by ajdirt** [RedNax67/MMM-WunderGround#14]
When I add this module to my mirror the screen goes black. Once I take it off again the mirror fuctions perfect. My code is as follows

{
module: 'mmm-wunderground',
Position: 'bottom_right',
Config: {
Apikey: 'xxxxxxxxxxxx',
Pws: 'NY/New_York',
        }
}

Not sure what's wrong

**Comment by dfuerst** [comment]
sure that you installed the module into the correct folder?
Had the same issue with an other module where i installed the module into the MagicMirror folder but should have done the clone into the modules subfolder

**Comment by Jlancel** [comment]
I had the same problem.  My module was located here;
~/MagicMirror/modules/default/MMM-WunderGround 

It needs to be in the root of the modules folder.

**Comment by dfuerst** [comment]
move the folder from MagicMirror/modules/default/     to MagicMirror/modules/

Gesendet von Yahoo Mail auf Android 
 
  Am Do., 22. Dez. 2016 um 20:47 hat Jlancel<notifications@github.com> Folgendes geschrieben:   
I have the same problem. My module is located here;
pi@raspberrypi:

/MagicMirror/modules/default/MMM-WunderGround $ ls
MMM-WunderGround.css MMM-WunderGround.js node_helper.js README.md translations

And my config.js has this
{
module: 'MMM-WunderGround',
position: 'top_right',
config: {
apikey: '0xxxxxxxxxx', // private; don't share!
pws: 'NY/Elmira',
lang : 'EN',
hourly : '1',
fctext : '1',
fcdaycount : "5",
fcdaystart : "0",
hourlyinterval : "3",
hourlycount : "2",
alerttime : 10000,
alerttruncatestring : ""
}
},
