### ISSUE TITLE
Missing Moon Phases Icon

### ISSUE THREAD

**Issue by lsumner4** [RedNax67/MMM-WunderGround#15]
After updating my MagicMirror2 software, the moon phases icon on the top right of the module has become a generic "Image missing" icon. I have tried uninstalling and reinstalling the module as well as my magicmirror software so I'm not sure where the issue lies. Strangely, I can see the moon phases just fine if I access my mirror software through a browser by going to the "Pi's IP address:8080".

**Comment by platox** [comment]
I am facing the same issue since a few days now with the same behavior.

**Comment by lsumner4** [comment]
@platox I solved the issue. It was due to my own mistake while installing the MagicMirror update, After you run "git pull" you must then run "npm install" from the MagicMirror folder (cd ~/MagigMirror)

**Comment by platox** [comment]
Hello. Thank you for the hint but it is not working for me. I have installed the mirror in December and it worked fine. The missing icon showed up 2 weeks ago and I haven't changed anything.
