### ISSUE TITLE
Floating Icons

### ISSUE THREAD

**Issue by in-a-days** [RedNax67/MMM-WunderGround#16]
I've got a couple random floating weather icons after installing this module.  It's def my favorite weather monitor and I'd love to figure out how to fix this. 
![icons](https://cloud.githubusercontent.com/assets/24900913/22233435/0200e1ca-e1a5-11e6-8da7-c61d848b7458.jpg)

**Comment by RedNax67** [comment]
Thats's.. new :) could you send me your config please?

**Comment by in-a-days** [comment]
Thanks for the reply!  Here's my config.

        {
            module: 'MMM-WunderGround',
            position: 'top_right',
            config: {
                apikey: 'xxxxxxxxxxxxxxx', // private; don't share!
                pws: 'NV/Henderson', 
                hourly: '1',
                fctext: '1',
                fcdaycount: "4",
                fcdaystart: "0",
                hourlyinterval: "2",
                hourlycount: "1",
                alerttime: 10000,
                alerttruncatestring: "english:",
            roundTmpDecs: 1,
            UseCardinals: 0,
            layout: "horizontal",
            sysstat: 0
            }
        },

**Comment by RedNax67** [comment]
Not able to replicate this behaviour using your config.... Could you try disabling the big moon module display (its the exact same picture as the small one top-right actually, just scaled up).

ALso, you don't seem to have any module down the middle section... This could be a factor. 

On the other hand... there seems to be no wind speed/direction at all (except for the floating one.. could be truncated by globale css...) 

![afbeelding](https://cloud.githubusercontent.com/assets/16489158/22237169/5ad6a0fe-e20a-11e6-99e5-85ee675cd9f7.png)

**Comment by in-a-days** [comment]
Disabling the moon didn't resolve the issue.  But I run a ton of modules and some of my formatting is... experimental?  I went with a totally basic config.js plus your module and the bug is gone.  I'm going to try to isolate the module that is creating the conflict and I will follow up.  But it def looks like an issue with my config rather than your module, thanks again!

**Comment by in-a-days** [comment]
So this appears to be the module creating the conflict:

https://github.com/chr1syy/MM-navbar
