### ISSUE TITLE
Problem with alerts / layout

### ISSUE THREAD

**Issue by djsunrise19** [RedNax67/MMM-WunderGround#2]
Hi,

yesterday we had three alerts (windy, rainy, thunderstorm) in my city in germany at the same time. So there are the following problems with that situation:

1) Alert String at the bottom of the current temperature is very long (no spaces between the alert messages. So the forecast has that "high width", too. Also the alert string is in english, my config is 'DL' -> German
2) The alert popups have no description. Only the title is visible.
3) The alert popups are on exactly the same position. So I can only read the last popup.

Any chances to fix that? Unfortunately, I'm no programmer.

Another Question: On the Website the alerts are in german. How can we add that feature?

Regards

**Comment by RedNax67** [comment]
Which weatherstation are you using in Germany? Maybe there's some special layout in the JSON package... Did you maybe make a screenshot of what happened?

I do now realise i'm not wordwrapping the alert string under the current weather display. Easy fix (when i get back home from work later today). 

Maybe i could just concatenate the alerts and put them in one box....

Watch this space :)

**Comment by RedNax67** [comment]
Ah, here's a thing:

The module uses translation to display the alert_type under the current conditions. I haven't provided a de.json as my german isn't up to that... so maybe you could help out and translate this so i can add a de.json to the repository?

{
  /\* GENERAL */
  "APIKEY": "Please set the correct openweather <i>appid</i> in the config for module: ",

```
"HUR":  "Hurricane Local Statement",
"TOR":  "Tornado Warning",
"TOW":  "Tornado Watch",
"WRN":  "Severe Thunderstorm Warning",
"SEW":  "Severe Thunderstorm Watch",
"WIN":  "Winter Weather Advisory",
"FLO":  "Flood Warning",
"WAT":  "Flood Watch / Statement",
"WND":  "High Wind Advisory",
"SVR":  "Severe Weather Statement",
"HEA":  "Heat Advisory",
"FOG":  "Dense Fog Advisory",
"SPE":  "Special Weather Statement",
"FIR":  "Fire Weather Advisory",
"VOL":  "Volcanic Activity Statement",
"HWW":  "Hurricane Wind Warning",
"REC":  "Record Set",
"REP":  "Public Reports",
"PUB":  "Public Information Statement"
```

}

**Comment by RedNax67** [comment]
Ok, couldn't resist it.... 

The code now concatenates multiple alerts strings into one message and displays it in the alert popup.

The alert string under the current conditions will be wordwrapped after concatenation. Shoeld fix your issue.

**Comment by djsunrise19** [comment]
@RedNax67 , thanks! I made a `de.json` file and a pull request. I'm not sure with `de` because in the weatherunderground api german is `dl`. Perhaps you have to rename that. I don't know, how your scripts are working.

**Comment by RedNax67** [comment]
Great!

Merged your commit and added a workaround for the weird code used by weatherunderground. Just set your language to DE, the module will then use DL in it's wu requests.

**Comment by djsunrise19** [comment]
Unfortunately not. If I change the language to `de`(like my mirror language) everything is in english. 

![image](https://cloud.githubusercontent.com/assets/14234570/15656513/71b60ee0-26a8-11e6-9f11-84831b000215.png)

With `dl` the short weather text is german, alert warnings arent.

![image](https://cloud.githubusercontent.com/assets/14234570/15656533/b57a3534-26a8-11e6-8a07-423e994143a7.png)

**Comment by RedNax67** [comment]
What language did you specify in your config?

If you set it to dl then the module will not recognise it and default back to english. 

Set the language to de and the script will substitute it with dl when requesting json from the wu api.

or you could git pull in about 5 mins and dl/de will be identical to the module :)

**Comment by djsunrise19** [comment]
MM² Config:
var config = {
    port: 8080,

```
language: 'de',
timeFormat: 24,
```

Module:
            module: 'MMM-WunderGround',
            position: 'top_right',
            config: {
                apikey: 'XXX',
                pws: 'Wismar Nord, Germany',
                lang: 'dl',

As I said, with `dl` it is in german, but not the alert messages (you can see that in my screenshots).

OK `git pull` in 5min :)

**Comment by RedNax67** [comment]
I get this (for my location):

var config = {
    port : 8080,

```
language : 'de',
timeFormat : 24,
units : 'metric',
```

![wunderground-de](https://cloud.githubusercontent.com/assets/16489158/15657499/aba6c3a2-26b1-11e6-8749-1595a46094ca.png)

**Comment by djsunrise19** [comment]
Yes, it works! Great!

**Comment by RedNax67** [comment]
Some spectacular weather you have there :)
