### ISSUE TITLE
in the evening, change forecast to show day forecast

### ISSUE THREAD

**Issue by dinkybluebug** [RedNax67/MMM-WunderGround#8]
during the day, the daily forecast shows predicted weather for the coming days.  During the evening, the daily forecast shows predicted weather for the following nights.  I can tell this  because of the moon shaped icons (rather than sun)

Is there a way that during the evening, the daily forecast shows weather forecast for the days coming up? (rather than night weather?)
![image](https://cloud.githubusercontent.com/assets/6286280/17910593/6ca3b710-6981-11e6-90ef-c64c68fe64e3.png)

**Comment by RedNax67** [comment]
Fixed in latest commit.

**Comment by dinkybluebug** [comment]
Great. thx
